# Vaccinations par pays

In [2]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
df_vaccin = pd.read_csv('country_vaccinations.csv')
df_vaccin_man = pd.read_csv('country_vaccinations_by_manufacturer.csv')

df_vaccin.head()

,country,iso_code,date,total_vaccinations,people_vaccinated,people_fully_vaccinated,daily_vaccinations_raw,daily_vaccinations,total_vaccinations_per_hundred,people_vaccinated_per_hundred,people_fully_vaccinated_per_hundred,daily_vaccinations_per_million,vaccines,source_name,source_website
0,Afghanistan,AFG,2021-02-22,0.0,0.0,NaN,NaN,NaN,0.0,0.0,NaN,NaN,"Johnson&Johnson, Oxford/AstraZeneca, Pfizer/Bi...",World Health Organization,https://covid19.who.int/
1,Afghanistan,AFG,2021-02-23,NaN,NaN,NaN,NaN,1367.0,NaN,NaN,NaN,34.0,"Johnson&Johnson, Oxford/AstraZeneca, Pfizer/Bi...",World Health Organization,https://covid19.who.int/
2,Afghanistan,AFG,2021-02-24,NaN,NaN,NaN,NaN,1367.0,NaN,NaN,NaN,34.0,"Johnson&Johnson, Oxford/AstraZeneca, Pfizer/Bi...",World Health Organization,https://covid19.who.int/
3,Afghanistan,AFG,2021-02-25,NaN,NaN,NaN,NaN,1367.0,NaN,NaN,NaN,34.0,"Johnson&Johnson, Oxford/AstraZeneca, Pfizer/Bi...",World Health Organization,https://covid19.who.int/
4,Afghanistan,AFG,2021-02-26,NaN,NaN,NaN,NaN,1367.0,NaN,NaN,NaN,34.0,"Johnson&Johnson, Oxford/AstraZeneca, Pfizer/Bi...",World Health Organization,https://covid19.who.int/

In [4]:
df_vaccin_man.head()

    location        date             vaccine  total_vaccinations
0  Argentina  2020-12-29             Moderna                   2
1  Argentina  2020-12-29  Oxford/AstraZeneca                   3
2  Argentina  2020-12-29   Sinopharm/Beijing                   1
3  Argentina  2020-12-29           Sputnik V               20481
4  Argentina  2020-12-30             Moderna                   2

## Visualisation du dataset principal "Vaccination par pays"

In [5]:
df_vaccin.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 86512 entries, 0 to 86511
Data columns (total 15 columns):
 #   Column                               Non-Null Count  Dtype
---  ------                               --------------  -----
 0   country                              86512 non-null  object
 1   iso_code                             86512 non-null  object
 2   date                                 86512 non-null  object
 3   total_vaccinations                   43607 non-null  float64
 4   people_vaccinated                    41294 non-null  float64
 5   people_fully_vaccinated              38802 non-null  float64
 6   daily_vaccinations_raw               35362 non-null  float64
 7   daily_vaccinations                   86213 non-null  float64
 8   total_vaccinations_per_hundred       43607 non-null  float64
 9   people_vaccinated_per_hundred        41294 non-null  float64
 10  people_fully_vaccinated_per_hundred  38802 non-null  float64
 11  daily_vaccinations_per_million       86213 non-null  float64
 12  vaccines                             86512 non-null  object
 13  source_name                          86512 non-null  object
 14  source_website                       86512 non-null  object
dtypes: float64(9), object(6)
memory usage: 9.9+ MB

In [6]:
df_vaccin.describe()

,total_vaccinations,people_vaccinated,people_fully_vaccinated,daily_vaccinations_raw,daily_vaccinations,total_vaccinations_per_hundred,people_vaccinated_per_hundred,people_fully_vaccinated_per_hundred,daily_vaccinations_per_million
count,4.360700e+04,4.129400e+04,3.880200e+04,3.536200e+04,8.621300e+04,43607.000000,41294.000000,38802.000000,86213.000000
mean,4.592964e+07,1.770508e+07,1.413830e+07,2.705996e+05,1.313055e+05,80.188543,40.927317,35.523243,3257.049157
std,2.246004e+08,7.078731e+07,5.713920e+07,1.212427e+06,7.682388e+05,67.913577,29.290759,28.376252,3934.312440
min,0.000000e+00,0.000000e+00,1.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000,0.000000,0.000000
25%,5.264100e+05,3.494642e+05,2.439622e+05,4.668000e+03,9.000000e+02,16.050000,11.370000,7.020000,636.000000
50%,3.590096e+06,2.187310e+06,1.722140e+06,2.530900e+04,7.343000e+03,67.520000,41.435000,31.750000,2050.000000
75%,1.701230e+07,9.152520e+06,7.559870e+06,1.234925e+05,4.409800e+04,132.735000,67.910000,62.080000,4682.000000
max,3.263129e+09,1.275541e+09,1.240777e+09,2.474100e+07,2.242429e+07,345.370000,124.760000,122.370000,117497.000000

## Nettoyage ou non des données

In [7]:
df_vaccin.isna().sum()

country                                    0
iso_code                                   0
date                                       0
total_vaccinations                     42905
people_vaccinated                      45218
people_fully_vaccinated                47710
daily_vaccinations_raw                 51150
daily_vaccinations                       299
total_vaccinations_per_hundred         42905
people_vaccinated_per_hundred          45218
people_fully_vaccinated_per_hundred    47710
daily_vaccinations_per_million           299
vaccines                                   0
source_name                                0
source_website                             0
dtype: int64

In [9]:
df_vaccin.isnull().sum()

country                                    0
iso_code                                   0
date                                       0
total_vaccinations                     42905
people_vaccinated                      45218
people_fully_vaccinated                47710
daily_vaccinations_raw                 51150
daily_vaccinations                       299
total_vaccinations_per_hundred         42905
people_vaccinated_per_hundred          45218
people_fully_vaccinated_per_hundred    47710
daily_vaccinations_per_million           299
vaccines                                   0
source_name                                0
source_website                             0
dtype: int64

Il semble que des données manquent pour certains pays.

In [10]:
len(df_vaccin['date'].unique())

483

Il y a à peu près 500 dates différentes pour chaque pays, voyons lesquels manquent de données.

In [22]:
country = df_vaccin['country'].unique().tolist()

for c in country:
    df_temp=df_vaccin[df_vaccin['country']==c]
    if df_temp['total_vaccinations'].isna().sum() != 0:
        valeurs_na = df_temp['total_vaccinations'].isna().sum()
        print(f'En ce qui concerne le pays du {c}, il manque {valeurs_na} valeurs pour les vaccinations totales')

En ce qui concerne le pays du Afghanistan, il manque 348 valeurs pour les vaccinations totales
En ce qui concerne le pays du Albania, il manque 191 valeurs pour les vaccinations totales
En ce qui concerne le pays du Algeria, il manque 381 valeurs pour les vaccinations totales
En ce qui concerne le pays du Andorra, il manque 371 valeurs pour les vaccinations totales
En ce qui concerne le pays du Angola, il manque 326 valeurs pour les vaccinations totales
En ce qui concerne le pays du Anguilla, il manque 366 valeurs pour les vaccinations totales
En ce qui concerne le pays du Antigua and Barbuda, il manque 302 valeurs pour les vaccinations totales
En ce qui concerne le pays du Armenia, il manque 305 valeurs pour les vaccinations totales
En ce qui concerne le pays du Aruba, il manque 91 valeurs pour les vaccinations totales
En ce qui concerne le pays du Australia, il manque 5 valeurs pour les vaccinations totales
En ce qui concerne le pays du Austria, il manque 378 valeurs pour les vaccinations totales
En ce qui concerne le pays du Azerbaijan, il manque 101 valeurs pour les vaccinations totales
En ce qui concerne le pays du Bahamas, il manque 327 valeurs pour les vaccinations totales
En ce qui concerne le pays du Bahrain, il manque 91 valeurs pour les vaccinations totales
En ce qui concerne le pays du Bangladesh, il manque 184 valeurs pour les vaccinations totales
En ce qui concerne le pays du Barbados, il manque 32 valeurs pour les vaccinations totales
En ce qui concerne le pays du Belarus, il manque 405 valeurs pour les vaccinations totales
En ce qui concerne le pays du Belize, il manque 268 valeurs pour les vaccinations totales
En ce qui concerne le pays du Benin, il manque 287 valeurs pour les vaccinations totales
En ce qui concerne le pays du Bermuda, il manque 378 valeurs pour les vaccinations totales
En ce qui concerne le pays du Bhutan, il manque 252 valeurs pour les vaccinations totales
En ce qui concerne le pays du Bolivia, il manque 4 valeurs pour les vaccinations totales
En ce qui concerne le pays du Bonaire Sint Eustatius and Saba, il manque 144 valeurs pour les vaccinations totales
En ce qui concerne le pays du Bosnia and Herzegovina, il manque 333 valeurs pour les vaccinations totales
En ce qui concerne le pays du Botswana, il manque 308 valeurs pour les vaccinations totales
En ce qui concerne le pays du Brazil, il manque 7 valeurs pour les vaccinations totales
En ce qui concerne le pays du British Virgin Islands, il manque 273 valeurs pour les vaccinations totales
En ce qui concerne le pays du Brunei, il manque 176 valeurs pour les vaccinations totales
En ce qui concerne le pays du Bulgaria, il manque 24 valeurs pour les vaccinations totales
En ce qui concerne le pays du Burkina Faso, il manque 268 valeurs pour les vaccinations totales
En ce qui concerne le pays du Burundi, il manque 122 valeurs pour les vaccinations totales
En ce qui concerne le pays du Cambodia, il manque 17 valeurs pour les vaccinations totales
En ce qui concerne le pays du Cameroon, il manque 291 valeurs pour les vaccinations totales
En ce qui concerne le pays du Canada, il manque 9 valeurs pour les vaccinations totales
En ce qui concerne le pays du Cape Verde, il manque 322 valeurs pour les vaccinations totales
En ce qui concerne le pays du Cayman Islands, il manque 350 valeurs pour les vaccinations totales
En ce qui concerne le pays du Central African Republic, il manque 289 valeurs pour les vaccinations totales
En ce qui concerne le pays du Chad, il manque 241 valeurs pour les vaccinations totales
En ce qui concerne le pays du China, il manque 85 valeurs pour les vaccinations totales
En ce qui concerne le pays du Colombia, il manque 95 valeurs pour les vaccinations totales
En ce qui concerne le pays du Comoros, il manque 304 valeurs pour les vaccinations totales
En ce qui concerne le pays du Congo, il manque 312 valeurs pour les vaccinations totales
En ce qui concerne le pays du Cook Islands, il manque 287 valeurs pour les vaccinations totales
En ce qui concerne le pays du Costa Rica, il manque 392 valeurs pour les vaccinations totales
En ce qui concerne le pays du Cote d'Ivoire, il manque 174 valeurs pour les vaccinations totales
En ce qui concerne le pays du Croatia, il manque 91 valeurs pour les vaccinations totales
En ce qui concerne le pays du Cuba, il manque 30 valeurs pour les vaccinations totales
En ce qui concerne le pays du Curacao, il manque 79 valeurs pour les vaccinations totales
En ce qui concerne le pays du Cyprus, il manque 249 valeurs pour les vaccinations totales
En ce qui concerne le pays du Democratic Republic of Congo, il manque 287 valeurs pour les vaccinations totales
En ce qui concerne le pays du Denmark, il manque 7 valeurs pour les vaccinations totales
En ce qui concerne le pays du Djibouti, il manque 318 valeurs pour les vaccinations totales
En ce qui concerne le pays du Dominica, il manque 325 valeurs pour les vaccinations totales
En ce qui concerne le pays du Dominican Republic, il manque 66 valeurs pour les vaccinations totales
En ce qui concerne le pays du Ecuador, il manque 11 valeurs pour les vaccinations totales
En ce qui concerne le pays du Egypt, il manque 348 valeurs pour les vaccinations totales
En ce qui concerne le pays du El Salvador, il manque 230 valeurs pour les vaccinations totales
En ce qui concerne le pays du Equatorial Guinea, il manque 303 valeurs pour les vaccinations totales
En ce qui concerne le pays du Eswatini, il manque 294 valeurs pour les vaccinations totales
En ce qui concerne le pays du Ethiopia, il manque 81 valeurs pour les vaccinations totales
En ce qui concerne le pays du Faeroe Islands, il manque 231 valeurs pour les vaccinations totales
En ce qui concerne le pays du Falkland Islands, il manque 61 valeurs pour les vaccinations totales
En ce qui concerne le pays du Fiji, il manque 327 valeurs pour les vaccinations totales
En ce qui concerne le pays du Finland, il manque 341 valeurs pour les vaccinations totales
En ce qui concerne le pays du French Polynesia, il manque 363 valeurs pour les vaccinations totales
En ce qui concerne le pays du Gabon, il manque 313 valeurs pour les vaccinations totales
En ce qui concerne le pays du Gambia, il manque 340 valeurs pour les vaccinations totales
En ce qui concerne le pays du Georgia, il manque 129 valeurs pour les vaccinations totales
En ce qui concerne le pays du Ghana, il manque 331 valeurs pour les vaccinations totales
En ce qui concerne le pays du Gibraltar, il manque 189 valeurs pour les vaccinations totales
En ce qui concerne le pays du Greece, il manque 19 valeurs pour les vaccinations totales
En ce qui concerne le pays du Greenland, il manque 276 valeurs pour les vaccinations totales
En ce qui concerne le pays du Grenada, il manque 341 valeurs pour les vaccinations totales
En ce qui concerne le pays du Guatemala, il manque 48 valeurs pour les vaccinations totales
En ce qui concerne le pays du Guernsey, il manque 321 valeurs pour les vaccinations totales
En ce qui concerne le pays du Guinea, il manque 217 valeurs pour les vaccinations totales
En ce qui concerne le pays du Guinea-Bissau, il manque 277 valeurs pour les vaccinations totales
En ce qui concerne le pays du Guyana, il manque 297 valeurs pour les vaccinations totales
En ce qui concerne le pays du Haiti, il manque 194 valeurs pour les vaccinations totales
En ce qui concerne le pays du Honduras, il manque 328 valeurs pour les vaccinations totales
En ce qui concerne le pays du Hong Kong, il manque 3 valeurs pour les vaccinations totales
En ce qui concerne le pays du Hungary, il manque 301 valeurs pour les vaccinations totales
En ce qui concerne le pays du Iceland, il manque 313 valeurs pour les vaccinations totales
En ce qui concerne le pays du India, il manque 11 valeurs pour les vaccinations totales
En ce qui concerne le pays du Indonesia, il manque 63 valeurs pour les vaccinations totales
En ce qui concerne le pays du Iran, il manque 298 valeurs pour les vaccinations totales
En ce qui concerne le pays du Iraq, il manque 330 valeurs pour les vaccinations totales
En ce qui concerne le pays du Ireland, il manque 4 valeurs pour les vaccinations totales
En ce qui concerne le pays du Isle of Man, il manque 173 valeurs pour les vaccinations totales
En ce qui concerne le pays du Jamaica, il manque 202 valeurs pour les vaccinations totales
En ce qui concerne le pays du Japan, il manque 113 valeurs pour les vaccinations totales
En ce qui concerne le pays du Jersey, il manque 285 valeurs pour les vaccinations totales
En ce qui concerne le pays du Jordan, il manque 224 valeurs pour les vaccinations totales
En ce qui concerne le pays du Kazakhstan, il manque 126 valeurs pour les vaccinations totales
En ce qui concerne le pays du Kenya, il manque 115 valeurs pour les vaccinations totales
En ce qui concerne le pays du Kiribati, il manque 279 valeurs pour les vaccinations totales
En ce qui concerne le pays du Kosovo, il manque 129 valeurs pour les vaccinations totales
En ce qui concerne le pays du Kuwait, il manque 413 valeurs pour les vaccinations totales
En ce qui concerne le pays du Kyrgyzstan, il manque 124 valeurs pour les vaccinations totales
En ce qui concerne le pays du Laos, il manque 287 valeurs pour les vaccinations totales
En ce qui concerne le pays du Latvia, il manque 10 valeurs pour les vaccinations totales
En ce qui concerne le pays du Lebanon, il manque 26 valeurs pour les vaccinations totales
En ce qui concerne le pays du Lesotho, il manque 362 valeurs pour les vaccinations totales
En ce qui concerne le pays du Liberia, il manque 295 valeurs pour les vaccinations totales
En ce qui concerne le pays du Libya, il manque 250 valeurs pour les vaccinations totales
En ce qui concerne le pays du Luxembourg, il manque 43 valeurs pour les vaccinations totales
En ce qui concerne le pays du Macao, il manque 126 valeurs pour les vaccinations totales
En ce qui concerne le pays du Madagascar, il manque 288 valeurs pour les vaccinations totales
En ce qui concerne le pays du Malawi, il manque 105 valeurs pour les vaccinations totales
En ce qui concerne le pays du Maldives, il manque 68 valeurs pour les vaccinations totales
En ce qui concerne le pays du Mali, il manque 315 valeurs pour les vaccinations totales
En ce qui concerne le pays du Malta, il manque 12 valeurs pour les vaccinations totales
En ce qui concerne le pays du Mauritania, il manque 296 valeurs pour les vaccinations totales
En ce qui concerne le pays du Mauritius, il manque 377 valeurs pour les vaccinations totales
En ce qui concerne le pays du Mexico, il manque 69 valeurs pour les vaccinations totales
En ce qui concerne le pays du Moldova, il manque 123 valeurs pour les vaccinations totales
En ce qui concerne le pays du Monaco, il manque 331 valeurs pour les vaccinations totales
En ce qui concerne le pays du Mongolia, il manque 112 valeurs pour les vaccinations totales
En ce qui concerne le pays du Montenegro, il manque 45 valeurs pour les vaccinations totales
En ce qui concerne le pays du Montserrat, il manque 376 valeurs pour les vaccinations totales
En ce qui concerne le pays du Morocco, il manque 192 valeurs pour les vaccinations totales
En ce qui concerne le pays du Mozambique, il manque 336 valeurs pour les vaccinations totales
En ce qui concerne le pays du Myanmar, il manque 384 valeurs pour les vaccinations totales
En ce qui concerne le pays du Namibia, il manque 227 valeurs pour les vaccinations totales
En ce qui concerne le pays du Nauru, il manque 335 valeurs pour les vaccinations totales
En ce qui concerne le pays du Nepal, il manque 241 valeurs pour les vaccinations totales
En ce qui concerne le pays du Netherlands, il manque 372 valeurs pour les vaccinations totales
En ce qui concerne le pays du New Caledonia, il manque 362 valeurs pour les vaccinations totales
En ce qui concerne le pays du New Zealand, il manque 1 valeurs pour les vaccinations totales
En ce qui concerne le pays du Nicaragua, il manque 353 valeurs pour les vaccinations totales
En ce qui concerne le pays du Niger, il manque 338 valeurs pour les vaccinations totales
En ce qui concerne le pays du Nigeria, il manque 280 valeurs pour les vaccinations totales
En ce qui concerne le pays du Niue, il manque 260 valeurs pour les vaccinations totales
En ce qui concerne le pays du North Macedonia, il manque 244 valeurs pour les vaccinations totales
En ce qui concerne le pays du Northern Cyprus, il manque 291 valeurs pour les vaccinations totales
En ce qui concerne le pays du Northern Ireland, il manque 12 valeurs pour les vaccinations totales
En ce qui concerne le pays du Oman, il manque 362 valeurs pour les vaccinations totales
En ce qui concerne le pays du Pakistan, il manque 226 valeurs pour les vaccinations totales
En ce qui concerne le pays du Palestine, il manque 198 valeurs pour les vaccinations totales
En ce qui concerne le pays du Panama, il manque 334 valeurs pour les vaccinations totales
En ce qui concerne le pays du Papua New Guinea, il manque 326 valeurs pour les vaccinations totales
En ce qui concerne le pays du Paraguay, il manque 172 valeurs pour les vaccinations totales
En ce qui concerne le pays du Philippines, il manque 185 valeurs pour les vaccinations totales
En ce qui concerne le pays du Pitcairn, il manque 80 valeurs pour les vaccinations totales
En ce qui concerne le pays du Poland, il manque 75 valeurs pour les vaccinations totales
En ce qui concerne le pays du Portugal, il manque 66 valeurs pour les vaccinations totales
En ce qui concerne le pays du Qatar, il manque 121 valeurs pour les vaccinations totales
En ce qui concerne le pays du Romania, il manque 1 valeurs pour les vaccinations totales
En ce qui concerne le pays du Russia, il manque 122 valeurs pour les vaccinations totales
En ce qui concerne le pays du Rwanda, il manque 312 valeurs pour les vaccinations totales
En ce qui concerne le pays du Saint Helena, il manque 86 valeurs pour les vaccinations totales
En ce qui concerne le pays du Saint Kitts and Nevis, il manque 296 valeurs pour les vaccinations totales
En ce qui concerne le pays du Saint Lucia, il manque 223 valeurs pour les vaccinations totales
En ce qui concerne le pays du Saint Vincent and the Grenadines, il manque 272 valeurs pour les vaccinations totales
En ce qui concerne le pays du Samoa, il manque 287 valeurs pour les vaccinations totales
En ce qui concerne le pays du San Marino, il manque 272 valeurs pour les vaccinations totales
En ce qui concerne le pays du Sao Tome and Principe, il manque 323 valeurs pour les vaccinations totales
En ce qui concerne le pays du Saudi Arabia, il manque 71 valeurs pour les vaccinations totales
En ce qui concerne le pays du Scotland, il manque 13 valeurs pour les vaccinations totales
En ce qui concerne le pays du Senegal, il manque 283 valeurs pour les vaccinations totales
En ce qui concerne le pays du Serbia, il manque 214 valeurs pour les vaccinations totales
En ce qui concerne le pays du Seychelles, il manque 351 valeurs pour les vaccinations totales
En ce qui concerne le pays du Sierra Leone, il manque 334 valeurs pour les vaccinations totales
En ce qui concerne le pays du Sint Maarten (Dutch part), il manque 279 valeurs pour les vaccinations totales
En ce qui concerne le pays du Slovakia, il manque 384 valeurs pour les vaccinations totales
En ce qui concerne le pays du Solomon Islands, il manque 340 valeurs pour les vaccinations totales
En ce qui concerne le pays du Somalia, il manque 287 valeurs pour les vaccinations totales
En ce qui concerne le pays du South Africa, il manque 121 valeurs pour les vaccinations totales
En ce qui concerne le pays du South Sudan, il manque 308 valeurs pour les vaccinations totales
En ce qui concerne le pays du Spain, il manque 151 valeurs pour les vaccinations totales
En ce qui concerne le pays du Sri Lanka, il manque 57 valeurs pour les vaccinations totales
En ce qui concerne le pays du Sudan, il manque 334 valeurs pour les vaccinations totales
En ce qui concerne le pays du Suriname, il manque 167 valeurs pour les vaccinations totales
En ce qui concerne le pays du Sweden, il manque 380 valeurs pour les vaccinations totales
En ce qui concerne le pays du Syria, il manque 361 valeurs pour les vaccinations totales
En ce qui concerne le pays du Taiwan, il manque 76 valeurs pour les vaccinations totales
En ce qui concerne le pays du Tajikistan, il manque 258 valeurs pour les vaccinations totales
En ce qui concerne le pays du Tanzania, il manque 215 valeurs pour les vaccinations totales
En ce qui concerne le pays du Thailand, il manque 46 valeurs pour les vaccinations totales
En ce qui concerne le pays du Timor, il manque 299 valeurs pour les vaccinations totales
En ce qui concerne le pays du Togo, il manque 336 valeurs pour les vaccinations totales
En ce qui concerne le pays du Tokelau, il manque 110 valeurs pour les vaccinations totales
En ce qui concerne le pays du Tonga, il manque 293 valeurs pour les vaccinations totales
En ce qui concerne le pays du Trinidad and Tobago, il manque 59 valeurs pour les vaccinations totales
En ce qui concerne le pays du Tunisia, il manque 67 valeurs pour les vaccinations totales
En ce qui concerne le pays du Turkey, il manque 3 valeurs pour les vaccinations totales
En ce qui concerne le pays du Turkmenistan, il manque 187 valeurs pour les vaccinations totales
En ce qui concerne le pays du Turks and Caicos Islands, il manque 419 valeurs pour les vaccinations totales
En ce qui concerne le pays du Tuvalu, il manque 172 valeurs pour les vaccinations totales
En ce qui concerne le pays du Uganda, il manque 252 valeurs pour les vaccinations totales
En ce qui concerne le pays du United Arab Emirates, il manque 81 valeurs pour les vaccinations totales
En ce qui concerne le pays du United Kingdom, il manque 1 valeurs pour les vaccinations totales
En ce qui concerne le pays du Uzbekistan, il manque 228 valeurs pour les vaccinations totales
En ce qui concerne le pays du Vanuatu, il manque 245 valeurs pour les vaccinations totales
En ce qui concerne le pays du Venezuela, il manque 374 valeurs pour les vaccinations totales
En ce qui concerne le pays du Vietnam, il manque 74 valeurs pour les vaccinations totales
En ce qui concerne le pays du Wales, il manque 5 valeurs pour les vaccinations totales
En ce qui concerne le pays du Wallis and Futuna, il manque 331 valeurs pour les vaccinations totales
En ce qui concerne le pays du Yemen, il manque 290 valeurs pour les vaccinations totales
En ce qui concerne le pays du Zambia, il manque 157 valeurs pour les vaccinations totales
En ce qui concerne le pays du Zimbabwe, il manque 25 valeurs pour les vaccinations totales